name: Context Examples
on: ['push']
jobs: 
  my-context:
    runs-on: ubuntu-latest
    steps: 
      
      - name: My Step
        run:  echo "Hello $MY_ACTON"
        env:
          MY_ACTION: ${{ github.action }}
