name: Node.js Hello World

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      # write console.log into hello.js with >
      - name: Run Hello World
        run: |
          echo "console.log('Hello World');" > hello.js 
          node hello.js
