name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show version
        run: node --version

      - name: Install dependencies
        run: npm install

      - name: Run app.js
        run: node app.js

      - name: Run Hello World
        run: |
          echo "console.log('Hello World');" > hello.js
          node hello.js
