name: Node.js CI

on: [push]

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - name: Show version
        run: node --version
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm app.js
