name: Run Bash Script
on: [push]
jobs: 
  example-job: 
    runs-on: ubuntu-latest
    # this means base directory
    defaults:
      run: 
        # use scripts directory in the root folder
        working-directory: ./scripts
    steps:
      - name: Check out the repository runner
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x ./scripts/my-script.sh ./scripts/my-another-script.sh
          
      - name: Run as script
        run: ./my-script.sh

      - name: Run antother script
        run: ./my-another-script.sh
