name: Run Bash Script
on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run the first script
        working-directory: ./scripts
        run: ./my-script.sh

      - name: Run the second script
        working-directory: ./scripts
        run: ./my-another-script.sh
