name: Worflow Commands
on: ['push']
jobs: 
  my-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Group Logging
        # multiline |
        run: |
          echo "::group:: My Group Message"
          echo "Msg 1"
          echo "Msg 2"
          echo "::endgroup::"
      - name: Step 1
        run: |
          echo "MY_VAL = hello" >> $GITGHUB_ENV
      - name: Step 2
        run: |
          echo $MY_VAL
          
